cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

damatex_overseas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^', include('damatex_overseas_app.urls', namespace='catalog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

damatex_overseas_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<file_name>[-\w]+)/$', views.Display, name='pdf_file'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^created/(?P<order_id>\d+)/$', views.order_created, name='order_created'),
    # url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    # url(r'^admin/order/(?P<order_id>\d+)/pdf/$',views.admin_order_pdf,name='admin_order_pdf'),


]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size': '2',
                                                                'value': '1', 'class': 'quantity', 'maxlength': '5'}),
                                  error_messages={'invalid': 'Please enter a valid quantity.'},
                                  min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from damatex_overseas_app.models import Product
from damatex_overseas_app.models import CarousalImages
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    carosual_images = CarousalImages.objects.all()
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    #coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'carosual_images': carosual_images})

templates/cart/detail.html
{% extends "shop/base3.html" %}
{% load static %}

{% block title %}
    Your inquiry Form
{% endblock %}

{% block carousel2 %}
    <div class="page-slider margin-bottom-35">
        <div id="carousel-example-generic" class="carousel slide carousel-slider">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% for item in carosual_images %}
                <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                {% endfor %}

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <!-- First slide -->
                <!-- carousel-item-four min height change from 580 to 380 -->
                {% for ci in carosual_images %}
                <div class="item {% if forloop.counter0 == 0 %}active{% endif %}" style="background-image: url('{{ ci.image_name.url }}')">
                    <div class="container">
                    </div>
                </div>
                {% endfor %}


            <!-- Controls -->
            <a class="left carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            <a class="right carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    </div>
{% endblock %}


{% block content %}
    <br/><br/>
    <div class="col-md-12 col-sm-12">
            <h1>Your inquiry Form</h1>
            <div class="goods-page">
              <div class="goods-data clearfix">
                <div class="table-wrapper-responsive">
                <table summary="Shopping cart">
                  <tr>
                    <th class="goods-page-image">Image</th>
                    <th class="goods-page-description">Description</th>
                    <th class="goods-page-quantity">Quantity</th>
                  </tr>
                   {% for item in cart %}
                      {% with product=item.product %}
                          <tr>
                            <td class="goods-page-image">
                              <a href="{{ product.get_absolute_url }}">
                                  <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                              </a>
                            </td>
                            <td class="goods-page-description">
                              <h3>{{ product.name }}</h3>
                            </td>

                            <td class="goods-page-quantity">
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td class="del-goods-col">
                              <a class="del-goods" href="{% url "cart:cart_remove" product.id %}">&nbsp;</a>
                            </td>
                          </tr>

                      {% endwith %}
                   {% endfor %}
                 </tr>
                </table>
                </div>
              </div>
              <a href="{% url "catalog:product_list" %}" class="btn btn-default">Continue Adding to Inquiry</a>
              <a href="{% url "orders:order_create" %}" class="btn btn-primary">Place Inquiry</a>
            </div>
          </div>

{% endblock %}