cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.contact, name='contactus'),

]

damatex_overseas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^', include('damatex_overseas_app.urls', namespace='catalog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

damatex_overseas_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<file_name>[-\w]+)/$', views.Display, name='pdf_file'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                Damatex Overseas Ind. Ltd.
            {% endblock %}
        </title>

        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>

    <body>
        <div id="header">
            <a href="/" class="logo">Damatex Overseas Ind. Ltd.</a>
        </div>

        <div id="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Your cart:
                        <a href="{% url "cart:cart_detail" %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}
                            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <div id="search">
{#            <form action="{% url 'shop:search' %}" method="get">#}
{#                <input type="text" placeholder="Search" aria-label="Search" name="q">#}
{#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#            </form>#}
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/shop/base3.html
<!DOCTYPE html>
{% load staticfiles %}
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->
<head>
  <meta charset="utf-8">

  <title>
      {% block title %}
        Damatex Overseas Ind. Ltd.
      {% endblock %}
  </title>
  <link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
{#  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">#}

  <meta content="Metronic Shop UI description" name="description">
  <meta content="Metronic Shop UI keywords" name="keywords">
  <meta content="keenthemes" name="author">

  <meta property="og:site_name" content="-CUSTOMER VALUE-">
  <meta property="og:title" content="-CUSTOMER VALUE-">
  <meta property="og:description" content="-CUSTOMER VALUE-">
  <meta property="og:type" content="website">
  <meta property="og:image" content="-CUSTOMER VALUE-"><!-- link to image for socio -->
  <meta property="og:url" content="-CUSTOMER VALUE-">

  <link rel="shortcut icon" href="favicon.ico">

  <!-- Fonts START -->
{#  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all" rel="stylesheet" type="text/css">#}
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Serif+Pro:200,300,400,600,700,900" rel="stylesheet">
  <!-- Fonts END -->

  <!-- Global styles START -->          
  <link href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Global styles END --> 
   
  <!-- Page level plugin styles START -->
  <link href="{% static 'assets/pages/css/animate.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/fancybox/source/jquery.fancybox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/owl.carousel/assets/owl.carousel.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/fancybox/source/jquery.fancybox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css">
  <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css"><!-- for slider-range -->
  <link href="{% static 'assets/plugins/rateit/src/rateit.css' %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin styles END -->

  <!-- Theme styles START -->
  <link href="{% static 'assets/pages/css/components.css' %}" rel="stylesheet">
  <link href="{% static 'assets/pages/css/slider.css' %}" rel="stylesheet">
  <link href="{% static 'assets/pages/css/style-shop.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'assets/corporate/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/corporate/css/style-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'assets/corporate/css/themes/red.css' %}" rel="stylesheet" id="style-color">
  <link href="{% static 'assets/corporate/css/custom.css' %}" rel="stylesheet">
  <!-- Theme styles END -->
</head>
<!-- Head END -->

<!-- Body BEGIN -->
<body class="ecommerce">
    <!-- BEGIN TOP BAR -->
    <div class="pre-header">
        <div class="container">
            <div class="row">
                <!-- BEGIN TOP BAR LEFT PART -->
                <div class="col-md-6 col-sm-6 additional-shop-info">
                    <ul class="list-unstyled list-inline">
                        <li><i class="fa fa-phone"></i><span> +971-551000831 </span></li>
                        <li><i class="fa fa-phone"></i><span> +971-509385876 </span></li>
                        <li><i class="fa fa-phone"></i><span> 8034554958 </span></li>

                    </ul>
                </div>
                <!-- END TOP BAR LEFT PART -->
            </div>
        </div>        
    </div>
    <!-- END TOP BAR -->

    <!-- BEGIN HEADER -->
    <div class="header">
      <div class="container">
        <a class="site-logo" href="{% url 'catalog:product_list' %}"><img src="{% static 'assets/corporate/img/logos/logo-shop-red.png' %}" alt="Damatex Overseas Ind. Ltd."></a>

        <a href="javascript:void(0);" class="mobi-toggler"><i class="fa fa-bars"></i></a>

        <!-- BEGIN CART -->
        <div class="top-cart-block">
          <div class="top-cart-info">
              {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                        <a href="{% url "cart:cart_detail" %}">
                            {{ total_items }} item{{ total_items|pluralize }}|
                        </a>
                {% else %}
                        Your enquiry list is empty.
                {% endif %}
              {% endwith %}
          </div>
          <i class="fa fa-shopping-cart"></i>
        </div>
        <!--END CART -->

        <!-- BEGIN NAVIGATION -->
        <div class="header-navigation">
          <ul>
            <!-- BEGIN TOP SEARCH -->
            <li class="menu-search">
              <div>
                <form action="{% url 'catalog:search' %}" method="get">
                  <div class="input-group">
                    <input type="text" placeholder="Search" class="form-control" name="q">
                    <span class="input-group-btn">
                      <button class="btn btn-primary" type="submit">Search</button>
                    </span>
                  </div>
                </form>
              </div> 
            </li>
            <!-- END TOP SEARCH -->
          </ul>
        </div>
        <!-- END NAVIGATION -->
      </div>
    </div>
    <!-- Header END -->
        <!-- BEGIN SLIDER -->

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for item in carosual_images %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
            {% endfor %}
        </ol>
    <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            {% for ci in carosual_images %}
                <div class="item {% if forloop.first %}active{% endif %}">
                    <img src="{{ ci.image_name.url }}" style="width:100%" alt="First slide">
                </div>
            {% endfor %}

            <!-- Controls -->
            <a class="left carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>

            <a class="right carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    {% block carousel %}

    {% endblock %}
    <!-- END SLIDER -->

    <div class="main">
      <div class="container">
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
          <!-- BEGIN SIDEBAR CATEGORY -->
          {% block category %}
              <br/><br/>
              <div class="sidebar col-md-3 col-sm-5">
              <ul class="list-group margin-bottom-25 sidebar-menu">
                  {% include 'shop/product/category_list.html' %}
              </ul>
              </div>
          {% endblock %}
          <!-- END SIDEBAR CATEGORY -->
          <!-- BEGIN CONTENT -->

          <div class="col-md-9 col-sm-7">
            <!-- BEGIN PRODUCT LIST -->
              {% block content %}

                </div>
              {% endblock %}
            <!-- END PRODUCT LIST -->
                <!-- BEGIN PAGINATOR -->
              {% if products.count > 24 %}
                  {% block pagination %}

                   {% endblock %}
              {% endif %}
                  <!-- END PAGINATOR -->
          </div>
          <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
      </div>
    </div>


    <!-- BEGIN PRE-FOOTER -->
    <div class="pre-footer">
      <div class="container">
        <div class="row">
          <!-- BEGIN BOTTOM ABOUT BLOCK -->
          <div class="col-md-3 col-sm-6 pre-footer-col">
            <h2>About us</h2>
            <p> Dubai quality mobile phone suppliers.</p>
            <p>Major Distributors BLU Mobiles.</p>
            <p> We can also supply others items with good price.</p>
          </div>
          <!-- END BOTTOM ABOUT BLOCK -->
          <!-- BEGIN BOTTOM INFO BLOCK -->
          <div class="col-md-3 col-sm-6 pre-footer-col">
            <h2>Information</h2>
            <ul class="list-unstyled">
              <li><i class="fa fa-angle-right"></i> <a href="{% url 'contact:contactus' %}">Contact Us</a></li>
            </ul>
          </div>
          <!-- END INFO BLOCK -->

          <!-- BEGIN BOTTOM CONTACTS -->
          <div class="col-md-3 col-sm-6 pre-footer-col">
            <h2>Our Contacts (DUBAI)</h2>
            <address class="margin-bottom-40">
              Al Nakhel Road<br>
              Opposite Talal Supermarket <br>
              Near Deira Park Hotel <br>
              Deira, Dubai, U.A.E <br>
              Mobile No.: +971 551000831 <br>
              Mobile No.: +971 509385876 <br>
              Whatsapp: +971 551000831 <br>
              Web-site: www.damatexoverseas.com
              E-mail: <a href="mailto:admin@damatexoverseas.com">admin@damatexoverseas.com</a><br>
            </address>
          </div>
          <div class="col-md-3 col-sm-6 pre-footer-col">
            <h2>Our Contacts (Nigeria)</h2>
            <address class="margin-bottom-40">
              5, Fraces Oremejis<br>
              Commuter Village<br>
              Ikeja Lagos, Nigeria <br>
              Mobile No.: 803455958
              Web-site: www.damatexoverseas.com
              E-mail: <a href="mailto:admin@damatexoverseas.com">admin@damatexoverseas.com</a><br>
            </address>
          </div>
          <!-- END BOTTOM CONTACTS -->
        </div>
        <hr>
      </div>
    </div>
    <!-- END PRE-FOOTER -->

    <!-- BEGIN FOOTER -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <!-- BEGIN COPYRIGHT -->
          <div class="col-md-4 col-sm-4 padding-top-10">
            2017 © Damatex Overseas Ind Ltd. ALL Rights Reserved.
          </div>
          <!-- END COPYRIGHT -->
          <!-- BEGIN PAYMENTS -->
          <div class="col-md-4 col-sm-4">

          </div>
          <!-- END PAYMENTS -->
          <!-- BEGIN POWERED -->
          <div class="col-md-4 col-sm-4 text-right">
            <p class="powered">Powered by: <a href="http://www.keenthemes.com/">KeenThemes.com</a></p>
          </div>
          <!-- END POWERED -->
        </div>
      </div>
    </div>
    <!-- END FOOTER -->

    <!-- Load javascripts at bottom, this will reduce page load time -->
    <!-- BEGIN CORE PLUGINS(REQUIRED FOR ALL PAGES) -->
    <!--[if lt IE 9]>
    <script src="{% static 'assets/plugins/respond.min.js' %}"></script>
    <![endif]-->  
    <script src="{% static 'assets/plugins/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/corporate/scripts/back-to-top.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->


    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="{% static 'assets/plugins/fancybox/source/jquery.fancybox.pack.js' %}" type="text/javascript"></script><!-- pop up -->
    <script src="{% static 'assets/plugins/owl.carousel/owl.carousel.min.js' %}" type="text/javascript"></script><!-- slider for products -->
    <script src='{% static 'assets/plugins/zoom/jquery.zoom.min.js' %}' type="text/javascript"></script><!-- product zoom -->
    <script src="{% static 'assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js' %}" type="text/javascript"></script><!-- Quantity -->
    <script src="{% static 'assets/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/rateit/src/jquery.rateit.js' %}" type="text/javascript"></script>
    <script src="{% static 'http://code.jquery.com/ui/1.10.3/jquery-ui.js' %}" type="text/javascript"></script><!-- for slider-range -->

    <script src="{% static 'assets/corporate/scripts/layout.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            Layout.init();    
            Layout.initOWL();
            Layout.initTwitter();
            Layout.initImageZoom();
            Layout.initTouchspin();
            Layout.initUniform();
            Layout.initSliderRange();
        });

    </script>

    <!-- END PAGE LEVEL JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>