cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

damatex_overseas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^', include('damatex_overseas_app.urls', namespace='catalog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

damatex_overseas_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<file_name>[-\w]+)/$', views.Display, name='pdf_file'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

damatex_overseas_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # for uploading pdf file
    product_pdffile = models.FileField()

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id,self.slug])


class ProductImages(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to='product/')

    def __str__(self):
        return self.product.name


class ProductDetail(models.Model):
    product = models.ForeignKey(Product, related_name='details')
    attribute = models.ForeignKey('ProductAttribute')
    value = models.CharField(max_length=500)
    description = models.TextField(blank=True)

    def __str__(self):
        return '%s: %s - %s' % (self.product,
                                 self.attribute,
                                 self.value)


class ProductAttribute(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    def __str__(self):
        return '%s' % self.name


class CarousalImages(models.Model):
    name = models.CharField(max_length=300)
    image_name = models.ImageField(upload_to='product/')

    def __str__(self):
        return self.name

templates/shop/product/category_list.html
{% with  active_categories as cats  %}
    <li class="list-group-item clearfix"><a href="{% url "catalog:product_list" %}"><i class="fa fa-angle-right"></i> All </a></li>

    {% for c in cats %}
        <li class="list-group-item clearfix"><i class="fa fa-angle-right"></i>
            {% ifequal c.get_absolute_url request_path %}
                {{ c.name }} <br/>
            {% else %}
                <a href="{{ c.get_absolute_url }}" class="category">{{ c.name }}</a>
            {% endifequal %}
        </li>
    {% endfor %}

{% endwith %}

templates/shop/product/detail.html
{% extends "shop/base3.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block carousel2 %}
    <div class="page-slider margin-bottom-35">
        <div id="carousel-example-generic" class="carousel slide carousel-slider">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% for item in carosual_images %}
                <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                {% endfor %}

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <!-- First slide -->
                <!-- carousel-item-four min height change from 580 to 380 -->
                {% for ci in carosual_images %}
                <div class="item {% if forloop.counter0 == 0 %}active{% endif %}" style="background-image: url('{{ ci.image_name.url }}')">
                    <div class="container">
                    </div>
                </div>
                {% endfor %}


            <!-- Controls -->
            <a class="left carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            <a class="right carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    </div>
{% endblock %}




{% block content %}
    <br/><br/>
    <div class="col-md-9 col-sm-7">
        <div >
          <div class="row">
            <div class="col-md-6 col-sm-6">
              <div class="product-main-image">
                <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}" class="img-responsive" data-BigImgsrc="{{ product.image.url }}">
              </div>

              <div class="product-other-images">
                {% for img in product.productimages_set.all %}
                    <a href="{{ img.image.url }}" class="fancybox-button" rel="photos-lib"><img alt="{{ product.name }}" src="{{ img.image.url }}"></a>
                {% endfor %}
              </div>
            </div>

            <div class="col-md-6 col-sm-6">
              <h1>{{ product.name }}</h1>
              <div class="description">
                <p>{{ product.description }}</p>
              </div>
              <div class="product-page-cart">

                    <form method="post" action="{% url 'cart:cart_add' product.id %}">
                        {% for field in cart_product_form %}

                        <div class="product-quantity">
                            {{ field  }}
                        </div>
                        {% csrf_token %}
                        {% endfor %}
                        <button class="btn btn-primary" type="submit">Add to enquiry list</button>

                  </form>

              </div>
            </div>
            <a href="{{ product.product_pdffile.url }}" target="_blank" class="btn btn-primary">Download Product Brochure</a>
            <div class="product-page-content">
              <ul id="myTab" class="nav nav-tabs">
                <li class="active"><a href="#Description" data-toggle="tab">Description</a></li>
                <li><a href="#Information" data-toggle="tab">Information</a></li>
                <li><a href="#Reviews" data-toggle="tab">Detail Guide</a></li>
              </ul>
              <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade in active" id="Description">
                  <p>{{ product.description }} </p>
                </div>
                <div class="tab-pane fade" id="Information">
                  <table class="datasheet">
                    <tr>
                      <th colspan="2">Additional features</th>
                    </tr>
                    <tr>
                      <td class="datasheet-features-type">Value 1</td>
                      <td>21 cm</td>
                    </tr>
                    <tr>
                      <td class="datasheet-features-type">Value 2</td>
                      <td>700 gr.</td>
                    </tr>
                    <tr>
                      <td class="datasheet-features-type">Value 3</td>
                      <td>10 person</td>
                    </tr>
                    <tr>
                      <td class="datasheet-features-type">Value 4</td>
                      <td>14 cm</td>
                    </tr>
                    <tr>
                      <td class="datasheet-features-type">Value 5</td>
                      <td>plastic</td>
                    </tr>
                  </table>
                </div>
                <div class="tab-pane" id="Reviews">
                   <a href="{{ product.product_pdffile.url }}" target="_blank" class="btn btn-primary">Download Product Brochure</a>
                </div>

                  <!-- END FORM-->
                </div>
              </div>
            </div>

            <div class="sticker sticker-sale"></div>
          </div>
        </div>
    </div>

{% endblock %}

templates/shop/product/list.html
{% extends "shop/base3.html" %}
{% load static %}
{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block carousel2 %}
<div id="carousel-example-generic" class="carousel slide " data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for item in carosual_images %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
        {% endfor %}
    </ol>
<!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        {% for ci in carosual_images %}
            <div class="item {% if forloop.first %}active{% endif %}">
                <img src="{{ ci.image_name.url }}" alt="First slide" width="100px" height="100px">
            </div>
        {% endfor %}

        <!-- Controls -->
        <a class="left carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="prev">
            <i class="fa fa-angle-left" aria-hidden="true"></i>
        </a>

        <a class="right carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="next">
            <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
    </div>
</div>
{% endblock %}



{% block content %}
    <div class="row product-list">
    {% for product in products %}

              <!-- PRODUCT ITEM START -->
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}" class="img-responsive" alt="{{ product.name }}" >
                    <div>
                      <a href="{{ product.image.url }}" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="{{ product.get_absolute_url }}" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
                </div>
              </div>
              <!-- PRODUCT ITEM END -->

    {% endfor %}
    </div>
{% endblock %}


{% block pagination %}
    <div class="row">
      <div class="col-md-4 col-sm-4 items-info">{{ products.count }}Items 1 to 9 of 10 total</div>
      <div class="col-md-8 col-sm-8">
        <ul class="pagination pull-right">
          <li><a href="javascript:;">&laquo;</a></li>
          <li><a href="javascript:;">1</a></li>
          <li><span>2</span></li>
          <li><a href="javascript:;">3</a></li>
          <li><a href="javascript:;">4</a></li>
          <li><a href="javascript:;">5</a></li>
          <li><a href="javascript:;">&raquo;</a></li>
        </ul>
      </div>
    </div>
{% endblock %}

templates/shop/product/search.html
{% extends 'shop/base3.html' %}
{% load static %}

{% block carousel %}
    <div class="page-slider margin-bottom-35">
        <div id="carousel-example-generic" class="carousel slide carousel-slider">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% for item in carosual_images %}
                <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                {% endfor %}

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <!-- First slide -->
                <!-- carousel-item-four min height change from 580 to 380 -->
                {% for ci in carosual_images %}
                <div class="item {% if forloop.counter0 == 0 %}active{% endif %}" style="background-image: url('{{ ci.image_name.url }}')">
                    <div class="container">
                    </div>
                </div>
                {% endfor %}


            <!-- Controls -->
            <a class="left carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            <a class="right carousel-control carousel-control-shop" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
    </div>
{% endblock %}



{% block content %}
    <br/>
    <div class="row product-list">
        {% for s in qs %}

              <!-- PRODUCT ITEM START -->
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="product-item">
                  <div class="pi-img-wrapper">
                    <img src="{% if s.image %}{{ s.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}" class="img-responsive" alt="{{ s.name }}" >
                    <div>
                      <a href="{{ s.image.url }}" class="btn btn-default fancybox-button">Zoom</a>
                      <a href="{{ s.get_absolute_url }}" class="btn btn-default fancybox-fast-view">View</a>
                    </div>
                  </div>
                  <h3><a href="{{ s.get_absolute_url }}">{{ s.name }}</a></h3>
                </div>
              </div>
              <!-- PRODUCT ITEM END -->
        {% empty %}
            <h2>No rusult found</h2>
        {% endfor %}

    </div>
{% endblock %}

{#{% block content2 %}#}
{#<div class="col-md-9 col-sm-7">#}
{#    <div class="content-search margin-bottom-20">#}
{#      <div class="row">#}
{#        <div class="col-md-6">#}
{#          <h1>Search result for <em>{{ query }}</em></h1>#}
{#        </div>#}
{##}
{#      </div>#}
{#    </div>#}
{##}
{#    <!-- BEGIN PRODUCT LIST -->#}
{#    {% for s in qs %}#}
{#          <div class="col-md-3 col-sm-3">#}
{#            <a href="{{ s.get_absolute_url }}">#}
{#                <img src="{% if s.image %}{{ s.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}" class="img-responsive" >#}
{#            </a>#}
{#            <center><h4>{{ s.name }}</h4></center>#}
{##}
{#          </div>#}
{#    {% empty %}#}
{#            <h2>No rusult found</h2>#}
{#    {% endfor %}#}
{#</div>#}
{#</div>#}
{#{% endblock %}#}